// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr5WrZZaGHylz0vDbfcy5KZaeUY1suNJk',
    appId: '1:593661824505:web:0bf0da414437465bcbc128',
    messagingSenderId: '593661824505',
    projectId: 'fitnow-a649e',
    authDomain: 'fitnow-a649e.firebaseapp.com',
    storageBucket: 'fitnow-a649e.firebasestorage.app',
    measurementId: 'G-4LP7GW04D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHRB2W1_OI6oyv1DyIYv4l8PTK9ERFIa4',
    appId: '1:593661824505:android:013a00f3d33fb396cbc128',
    messagingSenderId: '593661824505',
    projectId: 'fitnow-a649e',
    storageBucket: 'fitnow-a649e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCge80t_KdoRZciF0ieCk4jtaR7SnooqO0',
    appId: '1:593661824505:ios:8dee8f13f3c6b42acbc128',
    messagingSenderId: '593661824505',
    projectId: 'fitnow-a649e',
    storageBucket: 'fitnow-a649e.firebasestorage.app',
    iosBundleId: 'com.example.fitnowFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCge80t_KdoRZciF0ieCk4jtaR7SnooqO0',
    appId: '1:593661824505:ios:8dee8f13f3c6b42acbc128',
    messagingSenderId: '593661824505',
    projectId: 'fitnow-a649e',
    storageBucket: 'fitnow-a649e.firebasestorage.app',
    iosBundleId: 'com.example.fitnowFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr5WrZZaGHylz0vDbfcy5KZaeUY1suNJk',
    appId: '1:593661824505:web:aeb24fe6d6a886accbc128',
    messagingSenderId: '593661824505',
    projectId: 'fitnow-a649e',
    authDomain: 'fitnow-a649e.firebaseapp.com',
    storageBucket: 'fitnow-a649e.firebasestorage.app',
    measurementId: 'G-5BGMXZ6X7N',
  );
}
